[package]
name = "rested"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "rstd"
path = "src/main.rs"

[workspace]
members = ["lexer", "interpreter", "parser", "error_meta", "language_server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
clap_complete = "4.2.1"
interpreter = { path = "./interpreter" }
language_server = { path = "./language_server" }
lexer = { path = "./lexer" }
error_meta = { path = "./error_meta" }
colored = "2.0.0"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
